### ISSUE TITLE
Sorting provokes scroll bug on data change

### ISSUE THREAD

**Issue by greglds** [TanStack/react-table#3768] opened 2022-03-23 15:05 UTC
**Describe the bug (required)**
Without sorting, scroll doesn't change when I update my data. With sorting, it does.

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/gifted-frog-b53oli?file=/src/App.js:905-1008

**Steps To Reproduce (required)**

1. Click on _click me_ button in order to load data
2. Scroll down
3. Click on _click me_ button again
4. As data changes, it scrolls top, this is the problem
5. Remove sortBy / initalState by commenting lines 60 to 66
6. Repeat steps 2 to 3
7. It doesn't scroll top anymore

I tried memoizing the initial sortBy and passing as prop with no luck

**Expected behavior (Recommended)**
Should not scroll when data changes

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : Chrome + Firefox
- Chrome 99 + FF 98

**Comment by tannerlinsley** [comment] 2022-03-23 18:26
I'm not sure why this is happening TBH. But... the issue is completely gone in v8 :) https://codesandbox.io/s/magical-banach-nfumi6?file=/src/App.js

**Comment by greglds** [comment] 2022-03-23 20:28
The table is not sorted in your example, so I'm not sure the issue is gone 😮 
Thanks for the quick reply anyway 👍

**Comment by tannerlinsley** [comment] 2022-03-23 23:20
I’ll add sorting to my example, but even so I’ll get to the bottom of the v7 issue.

**Comment by greglds** [comment] 2022-04-05 13:29
Did you have a chance to look at the issue yet ? Thanks in advance.

**Comment by tannerlinsley** [comment] 2022-04-08 18:27
I'm not sure why this is happening in v7. Feel free to keep investigating, but I'm going to close this as I don't have bandwidth to dive into deep v7 bugs right now.

**Closed by tannerlinsley** 2022-04-08 18:27 UTC
Labels: v8
